
on:
  push:
    branches: [main]

name: user-service CI/CD pipeline

jobs:

  tests:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Run all Unit and Integration Test
        run: mvn test