
on:
  push:
    branches: [master]

name: user-service CI pipeline

jobs:

  tests:
    runs-on: ubuntu-latest
    environment: Dev

    steps:


      - name: Run Script file
        run: |
           chmod +x ./github/env.sh
           ./github/env.sh

      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Run all Unit and Integration Test
        run: mvn test

  package:
    needs: tests
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build Jar file and Upload artifacts
        run: mvn package

      - name: Upload jar to Artifactory
        uses: actions/upload-artifact@v3
        with:
          name: user-service-${{ github.sha }}
          path: ./target/*.jar


